#!/usr/bin/env bash
#PBS -q sequentiel
#PBS -l mem=20gb
#PBS -l walltime=00:30:00
#PBS -J 1-116
#PBS -N 00a_fastqc_raw

#declare variables used in the script
DATADIRECTORY=
DATAINPUT=path/to/raw/reads
DATAOUTPUT=path/to/output
FASTQCENV=path/to/binaries/or/conda
LOG=path/to/log


mkdir -p $DATAOUTPUT
mkdir -p $LOG

#Create a basename list that will serve us for future analyses
cd $DATAINPUT
basename -s .fastq.gz *.fastq.gz > $DATADIRECTORY/00_scripts/00_base_fastqc.txt

#Attribute a sample to the array variable
NAME=$(cat $DATADIRECTORY/00_scripts/00_base_fastqc.txt | awk "NR==${PBS_ARRAY_INDEX}")

#save array table correspondance
echo -e ${PBS_ARRAY_INDEX}"\t"${NAME} >> $DATADIRECTORY/00_scripts/00_fastqc_raw_array_table.txt

#Load Fastqc environment
$FASTQCENV

#Run commandline
fastqc $DATAINPUT/${NAME}.fastq.gz -o $DATAOUTPUT 2> $LOG/00a_fastqc_raw_${NAME}.log

#Deactivate environment (if conda)
conda deactivate
