#!/usr/bin/env bash
#PBS -q sequentiel
#PBS -l mem=20gb
#PBS -l walltime=04:00:00
#PBS -N 06_BCFtools

#To merge and filter the VCF file:

conda activate bcftools

DATADIRECTORY=$DATAWORK/evotox
DATAOUTPUT=$SCRATCH/evotox/RNAVAR

cd $DATAOUTPUT

mv ./results/variant_calling/*/*.vcf .
ls *.vcf > $DATADIRECTORY/00_scripts/vcf_merge_list.txt

bcftools merge -0 -l $DATADIRECTORY/00_scripts/vcf_merge_list.txt --threads 40 -o Evotox_SNPs.vcf.gz -O z

bcftools filter Evotox_SNPs.vcf.gz -e 'MIN(FORMAT/DP)<10 & MAF[0]<0.05' -o Evotox_SNPs_filtered.vcf.gz -O z --threads 40

conda deactivate
